version: '3.8'

services:
  backend:
    build: ./backend
    container_name: movielens_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///movielens.db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: movielens_frontend
    ports:
      - "80:8080"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: movielens_network